# Generated by Django 4.2.25 on 2025-10-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250)),
                ('isi', models.TextField(null=True)),
                ('categories', models.CharField(choices=[('python', 'python'), ('django', 'django'), ('javascript', 'javascript')], max_length=50)),
            ],
        ),
    ]
