# Generated by Django 4.2.25 on 2025-10-20 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(choices=[('python', 'python'), ('django', 'django'), ('javascript', 'javascript')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
