# Generated by Django 4.2.25 on 2025-11-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulangpergi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tujuan',
            name='profile',
            field=models.ImageField(blank=True, default='profil.png', upload_to=''),
        ),
    ]
