# Generated by Django 4.2.25 on 2025-11-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('kategori', models.CharField(choices=[('berita', 'Berita'), ('blog', 'Blog'), ('jurnal', 'Jurnal')], default='blog', max_length=20)),
            ],
        ),
    ]
