# Generated by Django 4.2.25 on 2025-11-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='penerbit',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='penulis',
            field=models.CharField(default='admin', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artikel',
            name='tag',
            field=models.CharField(default='admin', max_length=25),
            preserve_default=False,
        ),
    ]
